org: eduardoaragon
service: api-s3

provider:
  name: aws
  runtime: python3.12	
  # Default memory size for functions (default: 256MB)
  memorySize: 256
  timeout: 30
  iam:
    role: arn:aws:iam::634152101290:role/LabRole

functions:
  lista_buckets:
    handler: lista_buckets.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /s3/lista-buckets
          method: get
          cors: true
          integration: lambda
  lista_objetos_bucket:
    handler: lista_objetos_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket/lista-objetos
          method: post
          cors: true
          integration: lambda
  crear_bucket:
    handler: crear_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket
          method: post
          cors: true
          integration: lambda
  crear_directorio_bucket:
    handler: crear_directorio_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket/directorio
          method: post
          cors: true
          integration: lambda
  load_file_directorio_bucket:
    handler: load_file_directorio_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket/directorio/file
          method: post
          cors: true
          integration: lambda
